spring:
  application:
    name: constructor-articles-back
logging:
  file:
    name: logs/constructor-articles-back.log
jdbc:
  driverClassName:
  url:
  username:
  password:
hibernate:
  dialect:
  show_sql:
